.PHONY: all build test clean docker-build docker-push

all: build test

build:
	@echo "Compiling source files..."

test:
	@echo "Verifying everything works..."

clean:
	@echo "Removing temporary files..."

docker-build:
	@echo "Creating container image..."

docker-push:
	@echo "Uploading to registry..."
